[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
    "npm install -g serve",
    "cd frontend && npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "serve -s frontend/dist -l tcp://0.0.0.0:$PORT"

[variables]
NODE_ENV = "production"
VITE_API_URL = "https://backend-painel-universal-production.up.railway.app"